language: generic
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - gem install bundler
  - docker build -t vijay/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true vijay/react-test npm test -- --coverage

after_success:
  - docker build -t aviator429/vijay:multi-client ./client
  - docker build -t aviator429/vijay:multi-nginx ./nginx
  - docker build -t aviator429/vijay:multi-server ./server
  - docker build -t aviator429/vijay:multi-worker ./worker

# Login to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push Images to docker hub
  
  - docker push aviator429/vijay:multi-client
  - docker push aviator429/vijay:multi-nginx
  - docker push aviator429/vijay:multi-server
  - docker push aviator429/vijay:multi-worker

