language: ruby
sudo: required
services:
  - docker

before_install: gem install bundler
  - docker build -t vijay/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true vijay/docker-react npm run test -- --coverage

after_success:
  - docker build -t vijay/multi-client ./client
  - docker build -t vijay/multi-nginx ./nginx
  - docker build -t vijay/multi-server ./server
  - docker build -t vijay/multi-worker ./worker

# Login to docker hub

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push Images to docker hub
  
  - docker push vijay/multi-client
  - docker push vijay/multi-nginx
  - docker push vijay/multi-server
  - docker push vijay/multi-worker

